Trying to find the variance between BDE values and the features/descriptors given by MORDRED

In [1]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
from sklearn.linear_model import LinearRegression
from sklearn import datasets, linear_model
from sklearn.metrics import mean_squared_error, r2_score

In [2]:
features_df = pd.read_csv('SolventMordredResults_batch0.csv', on_bad_lines='skip')
features_df.head(5)

/var/folders/qc/kdqppv890tsc3zsxkk7rypjm0000gs/T/ipykernel_64804/3590084035.py:1: DtypeWarning: Columns (4,5,6,7,8,9,10,11,12,13,14,15,53,54,55,56,57,58,59,60,61,135,136,137,138,139,140,141,142,144,145,146,147,148,149,150,151,152,153,154,155,156,157,158,159,160,162,163,164,165,166,167,168,169,171,172,173,174,175,176,177,178,180,181,182,183,184,185,186,187,189,190,191,192,193,194,195,196,198,199,200,201,202,203,204,205,207,208,209,210,211,212,213,214,216,217,218,219,220,221,222,223,225,226,227,228,229,230,231,232,233,234,235,236,237,238,239,240,241,260,261,262,263,264,265,266,267,268,341,342,343,344,345,346,347,348,349,351,352,353,354,355,356,357,358,360,361,362,363,364,365,366,367,368,369,370,371,372,373,374,375,376,378,379,380,381,382,383,384,385,387,388,389,390,391,392,393,394,396,397,398,399,400,401,402,403,405,406,407,408,409,410,411,412,414,415,416,417,418,419,420,421,423,424,425,426,427,428,429,430,432,433,434,435,436,437,438,439,441,442,443,444,445,446,447,448,449,450,451,452,453,454,455,456,457,458,459,460,461,462,463,464,465,466,467,468,469,470,471,472,473,474,475,476,477,478,479,480,481,482,483,484,485,486,487,488,489,490,491,492,493,494,495,496,497,498,499,500,501,502,503,504,505,506,507,508,509,510,511,512,513,514,515,516,517,518,519,520,521,522,523,524,525,526,527,528,529,530,531,532,533,534,535,536,537,538,539,540,541,542,543,544,545,546,547,548,549,550,551,552,553,554,555,556,557,558,559,560,561,562,563,564,565,566,567,568,569,570,571,572,573,574,575,576,577,578,579,580,581,582,583,584,585,586,587,588,589,590,591,592,593,594,595,596,597,598,599,600,601,602,603,604,605,606,607,608,609,610,611,612,613,614,615,616,617,618,619,620,621,622,623,624,625,626,627,628,629,630,631,632,633,634,635,636,637,638,639,640,641,642,643,644,645,646,647,648,649,650,651,652,653,654,655,656,657,658,659,660,661,662,663,664,666,667,668,669,670,671,672,673,674,675,676,677,678,679,680,681,682,683,684,685,686,687,688,689,690,691,692,693,694,695,696,697,698,699,700,701,702,703,704,705,706,707,708,709,710,711,712,713,714,715,716,717,718,719,720,721,722,723,724,725,726,727,728,729,730,731,732,733,734,735,736,737,738,739,740,741,742,743,744,745,746,747,748,749,750,751,752,753,754,755,756,757,758,759,760,761,762,763,764,765,766,767,768,769,780,781,791,817,825,826,827,828,829,830,831,832,833,841,842,843,844,845,846,847,848,879,880,881,882,883,884,885,886,887,888,889,890,1055,1057,1060,1064,1065,1077,1078,1083,1084,1134,1136,1139,1143,1144,1156,1157,1162,1163,1208,1209,1210,1211,1212,1213,1214,1215,1216,1217,1218,1219,1220,1221,1222,1223,1224,1225,1226,1227,1228,1229,1230,1231,1232,1233,1234,1235,1236,1237,1238,1239,1240,1241,1242,1243,1244,1245,1246,1247,1248,1249,1250,1251,1252,1269,1270,1271,1272,1273,1274,1275,1276,1277,1278,1279,1280,1299,1300,1301,1359,1360,1361,1363,1364,1366,1369,1370,1371,1375,1376,1378,1379,1380,1381,1382,1383,1384,1385,1386,1387,1388,1389,1552,1580,1581,1582,1583,1611) have mixed types. Specify dtype option on import or set low_memory=False.
  features_df = pd.read_csv('SolventMordredResults_batch0.csv', on_bad_lines='skip')

,ABC,ABCGG,nAcid,nBase,SpAbs_A,SpMax_A,SpDiam_A,SpAD_A,SpMAD_A,LogEE_A,...,SRW10,TSRW10,MW,AMW,WPath,WPol,Zagreb1,Zagreb2,mZagreb1,mZagreb2
0,4.949747,5.143137,0,0,9.517541,1.879385,3.75877,9.517541,1.189693,2.876615,...,7.126891,32.187603,114.140851,4.390033,84,5,26.0,24.0,3.5,2.250000
1,5.059137,4.785854,0,0,8.720566,2.101003,4.202006,8.720566,1.245795,2.844305,...,8.124151,33.544698,92.062600,6.137507,42,5,30.0,31.0,2.361111111111111,1.666667
2,1.414214,1.414214,0,0,2.828427,1.414214,2.828427,2.828427,0.942809,1.849457,...,4.174387,17.310771,46.041865,5.115763,4,0,6.0,4.0,2.25,1.000000
3,4.242641,4.000000,0,0,8.0,2.0,4.0,8.0,1.333333,2.687624,...,7.627057,30.941317,88.052429,6.289459,27,3,24.0,24.0,1.5,1.500000
4,3.047207,3.305183,0,0,5.226252,1.847759,3.695518,5.226252,1.04525,2.408576,...,6.834109,27.254130,72.057515,5.542886,18,2,16.0,14.0,3.361111111111111,1.333333

So, there are 1613 different features/descriptors in the dataset. We need to figure out which are independent

In [3]:
SMILES_df = pd.read_csv('SoluteSmiles.txt', on_bad_lines='skip')
SMILES_df.drop_duplicates()

Empty DataFrame
Columns: [CCCCCCCC,  Cc1ccccc1,  CCO,  C1COCCO1,  CCC(C)=O,  Cc1ccccn1,  c1ccc2ccccc2c1,  Oc1ccccc1,  Cc1cccc(O)c1,  CC(O)=O,  CCC(O)=O,  CCCC(O)=O,  CN(C)C,  CCNCC,  c1ccncc1,  Nc1ccccc1,  N,  CN,  CC(C)CC(C)=O,  CCCCCCCC,  Cc1ccccc1.1,  CCO.1,  C1COCCO1.1,  CCC(C)=O.1,  CC(O)=O.1,  C[N+]([O-])=O,  CCCCCCCC.1,  Cc1ccccc1.2,  CCO.2,  C1COCCO1.2,  CCC(C)=O.2,  CC#N,  C[N+]([O-])=O.1,  CCCCCCCC.2,  Cc1ccccc1.3,  CCO.3,  C1COCCO1.3,  CCC(C)=O.3,  CC(=O)c1ccccc1,  CC(O)=O.2,  C[N+]([O-])=O.2,  OO,  CCCCCCCC.3,  Cc1ccccc1.4,  CCO.4,  C1COCCO1.4,  CCC(C)=O.4,  CC(O)=O.3,  CCC(O)=O.1,  Nc1ccccc1.1,  C[N+]([O-])=O.3,  OO.1,  CCCCCCCC.4,  Cc1ccccc1.5,  CCO.5,  C1COCCO1.5,  COc1ccccc1,  CCC(C)=O.5,  CCCCN,  C[N+]([O-])=O.4,  CCCCC,  CCCCCC,  CCCCCCCC.5,  C1CCCCC1,  c1ccccc1,  Cc1ccccc1.6,  CO,  CCO.6,  CCCO,  CC(C)O,  CCCCO,  CC(C)(C)O,  CCCCCO,  Oc1ccccc1.1,  CCCCCCO,  Cc1ccccc1O,  Cc1cccc(O)c1.1,  Cc1ccc(O)cc1,  CCCCCCCO,  C1COCCO1.6,  CC(C)=O,  CCC(C)=O.6,  CCCC(C)=O,  CCCCC(C)=O,  CCCCCC(C)=O,  CC(O)=O.4,  CCC(O)=O.2,  CCCC(O)=O.1,  CCCCC(O)=O,  CCCCCC(O)=O,  COC(C)=O,  CCC(=O)OC,  CCOC(C)=O,  CCCOC(C)=O,  CCCCC(=O)OC,  CCCCOC(C)=O,  CCCCCC(=O)OC,  CCCCCOC(C)=O,  CCN,  CNC, ...]
Index: []

[0 rows x 25333 columns]

In [4]:
frames = [features_df, SMILES_df]
result = pd.concat(frames)
display(result)

,ABC,ABCGG,nAcid,nBase,SpAbs_A,SpMax_A,SpDiam_A,SpAD_A,SpMAD_A,LogEE_A,...,Cc1c(O)cccc1O.1,c1ccc(cc1)c2ccccc2.1,[O-][N+](=O)c1cccc2c1cccc2[N+]([O-])=O,OC[P]1(=O)Oc2ccccc2c3ccccc13,COc1ccc(cc1OC)C(=O)N2CCN(CC2)c3ccc4NC(=O)CCc4c3,Cc1ccc2[nH]c(Nc3ccccc3)nc2c1,Cc1ccccc1C(O)=O.1,Cc1cc(cc(c1O)[N+]([O-])=O)[N+]([O-])=O.1,CN(C)c1ccc(cc1)C(=Nc2ccccc2N)c3ccc(cc3)N(C)C,
0,4.949747,5.143137,0.0,0.0,9.517541,1.879385,3.75877,9.517541,1.189693,2.876615,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,5.059137,4.785854,0.0,0.0,8.720566,2.101003,4.202006,8.720566,1.245795,2.844305,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2,1.414214,1.414214,0.0,0.0,2.828427,1.414214,2.828427,2.828427,0.942809,1.849457,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3,4.242641,4.000000,0.0,0.0,8.0,2.0,4.0,8.0,1.333333,2.687624,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4,3.047207,3.305183,0.0,0.0,5.226252,1.847759,3.695518,5.226252,1.04525,2.408576,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
12464,5.766244,5.909452,0.0,1.0,9.910095,2.224503,4.19461,9.910095,1.238762,2.984531,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
12465,5.875634,5.943785,1.0,1.0,10.251662,1.961571,3.923141,10.251662,1.139074,3.007497,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
12466,5.875634,5.943785,1.0,1.0,10.251662,1.961571,3.923141,10.251662,1.139074,3.007497,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
12467,7.289847,7.007240,1.0,0.0,12.784906,1.975377,3.950753,12.784906,1.162264,3.210676,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
12468,7.289847,7.007240,1.0,0.0,12.784906,1.975377,3.950753,12.784906,1.162264,3.210676,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

For tomorrow, does this df look the way it should?
Are the SMILES strings supposed to be indivodual columns? Or is there supposed to be a smiles string column
with the strings as the values inside instead of NA?